services:
  - type: web
    name: unilever-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unilever-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: unilever-db
    plan: free
    databaseName: unilever
    user: unilever_user
